name: PMail
version: 1.0 Alpha
authors: [chenhao]
main: com.chenhao220.PlayerMail.Load

commands:
  PMail:
    description: Displays information about redpack
    usage: /<command>
    
permissions:
  PMail.Admin:
    description: Notifies the player when vault is in need of an update.
    default: op